// ignore_for_file: require_trailing_commas

import 'package:festival_frame/models/frame_model.dart';
import 'package:flutter/material.dart';
import 'package:on_image_matrix/on_image_matrix.dart';

List<ColorFilter> filterList = [
  OnImageFilters.normal,
  OnImageFilters.blueSky,
  OnImageFilters.gray,
  OnImageFilters.grayHighBrightness,
  OnImageFilters.grayHighExposure,
  OnImageFilters.grayLowBrightness,
  const ColorFilter.srgbToLinearGamma(),
  const ColorFilter.mode(Colors.grey, BlendMode.darken),
  OnImageFilters.hueRotateWith2,
  OnImageFilters.invert,
  OnImageFilters.kodachrome,
  OnImageFilters.protanomaly,
  OnImageFilters.random,
  OnImageFilters.sepia,
  OnImageFilters.sepium,
  OnImageFilters.technicolor,
  OnImageFilters.vintage,
];

List<FrameData> fImage = <FrameData>[
  FrameData(
    img: '',
    name: 'Navratri',
    list: [
      "assets/images/n11.png",
      "assets/images/n14.png",
      "assets/images/n16.png",
      "assets/images/n21.png",
      "assets/images/n19.png",
      "assets/images/n20.png",
      "assets/images/n22.png",
      "assets/images/n23.png",
      "assets/images/n24.png",
      "assets/images/n25.png",
      "assets/images/n26.png",
      "assets/images/n27.png",
      "assets/images/n28.png",
      "assets/images/n29.png",
      "assets/images/n30.png",
      "assets/images/n31.png",
      "assets/images/n32.png",
      "assets/images/n33.png",
      "assets/images/n34.png",
      "assets/images/n35.png",
      "assets/images/n10.png",
    ],
    sticker: [
      Image.asset("assets/sticker/ns1.png"),
      Image.asset("assets/sticker/ns2.png"),
      Image.asset("assets/sticker/ns3.png"),
      Image.asset("assets/sticker/ns4.png"),
      Image.asset("assets/sticker/ns5.png"),
      Image.asset("assets/sticker/ns6.png"),
      Image.asset("assets/sticker/ns7.png"),
      Image.asset("assets/sticker/ns8.png"),
      Image.asset("assets/sticker/ns9.png"),
      Image.asset("assets/sticker/ns10.png"),
      Image.asset("assets/sticker/ns11.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Diwali',
    list: [
      "assets/images/d2.png",
      "assets/images/d3.png",
      "assets/images/d6.png",
      "assets/images/d7.png",
      "assets/images/d8.png",
      "assets/images/d9.png",
      "assets/images/d10.png",
      "assets/images/d11.png",
      "assets/images/d13.png",
      "assets/images/d14.png",
      "assets/images/d15.png",
      "assets/images/d16.png",
      "assets/images/d17.png",
      "assets/images/d18.png",
      "assets/images/d19.png",
      "assets/images/d20.png",
      "assets/images/d21.png",
      "assets/images/d22.png",
      "assets/images/d23.png",
      "assets/images/d24.png",
      "assets/images/d25.png",
      "assets/images/d26.png",
      "assets/images/d27.png",
      "assets/images/d28.png",
      "assets/images/d29.png",
    ],
    sticker: [
      Image.asset("assets/sticker/ds1.png"),
      Image.asset("assets/sticker/ds2.png"),
      Image.asset("assets/sticker/ds3.png"),
      Image.asset("assets/sticker/ds4.png"),
      Image.asset("assets/sticker/ds5.png"),
      Image.asset("assets/sticker/ds6.png"),
      Image.asset("assets/sticker/ds7.png"),
      Image.asset("assets/sticker/ds8.png"),
      Image.asset("assets/sticker/ds9.png"),
      Image.asset("assets/sticker/ds10.png"),
      Image.asset("assets/sticker/ds11.png"),
      Image.asset("assets/sticker/ds12.png"),
      Image.asset("assets/sticker/ds13.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Rakhi',
    list: [
      "assets/images/r1.png",
      "assets/images/r5.png",
      "assets/images/r6.png",
      "assets/images/r8.png",
      "assets/images/r11.png",
      "assets/images/r12.png",
      "assets/images/r27.png",
      "assets/images/r14.png",
      "assets/images/r34.png",
      "assets/images/r35.png",
      "assets/images/r36.png",
      "assets/images/r16.png",
      "assets/images/r17.png",
      "assets/images/r18.png",
      "assets/images/r28.png",
      "assets/images/r20.png",
      "assets/images/r21.png",
      "assets/images/r22.png",
      "assets/images/r23.png",
      "assets/images/r24.png",
      "assets/images/r25.png",
      "assets/images/r26.png",
    ],
    sticker: [
      Image.asset("assets/sticker/rs1.png"),
      Image.asset("assets/sticker/rs2.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Makar Sankranti',
    list: [
      "assets/images/m25.png",
      "assets/images/m26.png",
      "assets/images/m27.png",
      "assets/images/m7.png",
      "assets/images/m8.png",
      "assets/images/m9.png",
      "assets/images/m10.png",
      "assets/images/m12.png",
      "assets/images/m13.png",
      "assets/images/m14.png",
      "assets/images/m15.png",
      "assets/images/m16.png",
      "assets/images/m17.png",
      "assets/images/m18.png",
      "assets/images/m19.png",
      "assets/images/m20.png",
      "assets/images/m21.png",
      "assets/images/m22.png",
      "assets/images/m23.png",
      "assets/images/m24.png",
    ],
    sticker: [
      Image.asset("assets/sticker/ms1.png"),
      Image.asset("assets/sticker/ms2.png"),
      Image.asset("assets/sticker/ms3.png"),
      Image.asset("assets/sticker/ms4.png"),
      Image.asset("assets/sticker/ms5.png"),
      Image.asset("assets/sticker/ms6.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Holi',
    list: [
      "assets/images/h4.png",
      "assets/images/h8.png",
      "assets/images/h26.png",
      "assets/images/h25.png",
      "assets/images/h11.png",
      "assets/images/h12.png",
      "assets/images/h21.png",
      "assets/images/h13.png",
      "assets/images/h22.png",
      "assets/images/h23.png",
      "assets/images/h24.png",
      "assets/images/h14.png",
      "assets/images/h15.png",
      "assets/images/h16.png",
      "assets/images/h29.png",
      "assets/images/h27.png",
      "assets/images/h28.png",
      "assets/images/h32.png",
      "assets/images/h33.png",
      "assets/images/h34.png",
      "assets/images/h35.png",
      "assets/images/h18.png",
      "assets/images/h19.png",
    ],
    sticker: [
      Image.asset("assets/sticker/hs1.png"),
      Image.asset("assets/sticker/hs2.png"),
      Image.asset("assets/sticker/hs3.png"),
      Image.asset("assets/sticker/hs4.png"),
      Image.asset("assets/sticker/hs5.png"),
      Image.asset("assets/sticker/hs6.png"),
      Image.asset("assets/sticker/hs7.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Janmashtmi',
    list: [
      "assets/images/j3.png",
      "assets/images/j5.png",
      "assets/images/j7.png",
      "assets/images/j8.png",
      "assets/images/j11.png",
      "assets/images/j23.png",
      "assets/images/j20.png",
      "assets/images/j21.png",
      "assets/images/j22.png",
      "assets/images/j19.png",
      "assets/images/j15.png",
      "assets/images/j16.png",
      "assets/images/j17.png",
      "assets/images/j24.png",
      "assets/images/j25.png",
      "assets/images/j26.png",
      "assets/images/j27.png",
      "assets/images/j28.png",
      "assets/images/j29.png",
      "assets/images/j30.png",
    ],
    sticker: [
      Image.asset("assets/sticker/js1.png"),
      Image.asset("assets/sticker/js2.png"),
      Image.asset("assets/sticker/js3.png"),
      Image.asset("assets/sticker/js4.png"),
      Image.asset("assets/sticker/js5.png"),
      Image.asset("assets/sticker/js6.png"),
      Image.asset("assets/sticker/js7.png"),
      Image.asset("assets/sticker/js8.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Marry Chrishmas',
    list: [
      "assets/images/c6.png",
      "assets/images/c8.png",
      "assets/images/c9.png",
      "assets/images/c11.png",
      "assets/images/c12.png",
      "assets/images/c16.png",
      "assets/images/c17.png",
      "assets/images/c20.png",
      "assets/images/c21.png",
      "assets/images/c22.png",
      "assets/images/c23.png",
      "assets/images/c24.png",
      "assets/images/c25.png",
      "assets/images/c26.png",
      "assets/images/c27.png",
      "assets/images/c28.png",
      "assets/images/c29.png",
      "assets/images/c30.png",
      "assets/images/c31.png",
      "assets/images/c32.png",
      "assets/images/c33.png",
      "assets/images/c34.png",
      "assets/images/c35.png",
    ],
    sticker: [
      Image.asset("assets/sticker/cs1.png"),
      Image.asset("assets/sticker/cs2.png"),
      Image.asset("assets/sticker/cs3.png"),
      Image.asset("assets/sticker/cs4.png"),
      Image.asset("assets/sticker/cs5.png"),
      Image.asset("assets/sticker/cs6.png"),
      Image.asset("assets/sticker/cs7.png"),
      Image.asset("assets/sticker/cs8.png"),
      Image.asset("assets/sticker/cs9.png"),
      Image.asset("assets/sticker/cs10.png"),
      Image.asset("assets/sticker/cs11.png"),
      Image.asset("assets/sticker/cs12.png"),
      Image.asset("assets/sticker/cs13.png"),
      Image.asset("assets/sticker/cs14.png"),
      Image.asset("assets/sticker/cs15.png"),
      Image.asset("assets/sticker/cs16.png"),
      Image.asset("assets/sticker/cs17.png"),
      Image.asset("assets/sticker/cs18.png"),
      Image.asset("assets/sticker/cs19.png"),
      Image.asset("assets/sticker/cs20.png"),
      Image.asset("assets/sticker/cs21.png"),
      Image.asset("assets/sticker/cs22.png"),
      Image.asset("assets/sticker/cs23.png"),
      Image.asset("assets/sticker/cs24.png"),
      Image.asset("assets/sticker/cs25.png"),
      Image.asset("assets/sticker/cs26.png"),
      Image.asset("assets/sticker/cs27.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'New Year',
    list: [
      'assets/images/y1.png',
      'assets/images/y2.png',
      'assets/images/y3.png',
      'assets/images/y4.png',
      'assets/images/y5.png',
      'assets/images/y6.png',
      'assets/images/y7.png',
      'assets/images/y8.png',
      'assets/images/y9.png',
      'assets/images/y10.png',
      'assets/images/y11.png',
      'assets/images/y12.png',
      'assets/images/y13.png',
      'assets/images/y14.png',
      'assets/images/y15.png',
      'assets/images/y16.png',
      'assets/images/y17.png',
      'assets/images/y18.png',
    ],
    sticker: [
      Image.asset("assets/sticker/ys1.png"),
      Image.asset("assets/sticker/ys2.png"),
      Image.asset("assets/sticker/ys3.png"),
      Image.asset("assets/sticker/ys4.png"),
      Image.asset("assets/sticker/ys5.png"),
      Image.asset("assets/sticker/ys6.png"),
      Image.asset("assets/sticker/ys7.png"),
      Image.asset("assets/sticker/ys8.png"),
      Image.asset("assets/sticker/ys9.png"),
      Image.asset("assets/sticker/ys10.png"),
      Image.asset("assets/sticker/ys11.png"),
      Image.asset("assets/sticker/ys12.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Ganesh Chaturthi',
    list: [
      "assets/images/g1.png",
      // "assets/images/g4.png",
      "assets/images/g3.png",
      "assets/images/g11.png",
      "assets/images/g5.png",
      "assets/images/g6.png",
      "assets/images/g12.png",
      "assets/images/g13.png",
      "assets/images/g14.png",
      "assets/images/g8.png",
      "assets/images/g9.png",
      "assets/images/g17.png",
      "assets/images/g15.png",
      "assets/images/g16.png",
      "assets/images/g18.png",
      "assets/images/g19.png",
      "assets/images/g20.png",
      "assets/images/g21.png",
      "assets/images/g22.png",
      "assets/images/g23.png",
      "assets/images/g24.png",
      "assets/images/g25.png",
      "assets/images/g26.png",
      "assets/images/g27.png",
      "assets/images/g28.png",
      "assets/images/g29.png",
      "assets/images/g30.png",
      "assets/images/g31.png",
    ],
    sticker: [
      Image.asset("assets/sticker/gs1.png"),
      Image.asset("assets/sticker/gs2.png"),
      Image.asset("assets/sticker/gs3.png"),
      Image.asset("assets/sticker/gs4.png"),
      Image.asset("assets/sticker/gs5.png"),
      Image.asset("assets/sticker/gs6.png"),
      Image.asset("assets/sticker/gs7.png"),
      Image.asset("assets/sticker/gs8.png"),
      Image.asset("assets/sticker/gs9.png"),
      Image.asset("assets/sticker/gs10.png"),
      Image.asset("assets/sticker/gs11.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
  FrameData(
    img: '',
    name: 'Independence Day',
    list: [
      "assets/images/i3.png",
      "assets/images/i5.png",
      "assets/images/i14.png",
      "assets/images/i6.png",
      "assets/images/i8.png",
      "assets/images/i10.png",
      "assets/images/i16.png",
      "assets/images/i12.png",
      "assets/images/i22.png",
      "assets/images/i17.png",
      "assets/images/i18.png",
      "assets/images/i19.png",
      "assets/images/i20.png",
      "assets/images/i21.png",
      "assets/images/i23.png",
      "assets/images/i25.png",
      "assets/images/i26.png",
      "assets/images/i27.png",
      "assets/images/i28.png",
      "assets/images/i29.png",
      "assets/images/i30.png",
      "assets/images/i31.png",
      "assets/images/i32.png",
      "assets/images/i33.png",
      "assets/images/i34.png",
      "assets/images/i35.png",
      "assets/images/i36.png",
      "assets/images/i37.png",
    ],
    sticker: [
      Image.asset("assets/sticker/is1.png"),
      Image.asset("assets/sticker/is2.png"),
      Image.asset("assets/sticker/is3.png"),
      Image.asset("assets/sticker/is4.png"),
      Image.asset("assets/sticker/is5.png"),
      Image.asset("assets/sticker/is6.png"),
      Image.asset("assets/sticker/is7.png"),
      Image.asset("assets/sticker/is8.png"),
      Image.asset("assets/sticker/is9.png"),
      Image.asset("assets/sticker/is10.png"),
      Image.asset("assets/sticker/is11.png"),
      Image.asset("assets/sticker/s1.png"),
      Image.asset("assets/sticker/s2.png"),
      Image.asset("assets/sticker/s3.png"),
      Image.asset("assets/sticker/s4.png"),
      Image.asset("assets/sticker/s5.png"),
      Image.asset("assets/sticker/s6.png"),
      Image.asset("assets/sticker/s7.png"),
      Image.asset("assets/sticker/s8.png"),
      Image.asset("assets/sticker/s9.png"),
      Image.asset("assets/sticker/s10.png"),
      Image.asset("assets/sticker/s11.png"),
      Image.asset("assets/sticker/s12.png"),
      Image.asset("assets/sticker/s13.png"),
      Image.asset("assets/sticker/s14.png"),
      Image.asset("assets/sticker/s15.png"),
      Image.asset("assets/sticker/s16.png"),
      Image.asset("assets/sticker/s17.png"),
      Image.asset("assets/sticker/s18.png"),
      Image.asset("assets/sticker/s19.png"),
      Image.asset("assets/sticker/s20.png"),
      Image.asset("assets/sticker/s21.png"),
      Image.asset("assets/sticker/s22.png"),
      Image.asset("assets/sticker/s23.png"),
    ],
  ),
];

List<DrawerFilter> drawerField = <DrawerFilter>[
  DrawerFilter(img: 'assets/iconImage/dandiya.png', name: 'Navratri'),
  DrawerFilter(img: 'assets/iconImage/diya.png', name: 'Diwali'),
  DrawerFilter(img: 'assets/iconImage/rakhi.png', name: 'Rakhi'),
  DrawerFilter(img: 'assets/iconImage/kite.png', name: 'Makar Sankranti'),
  DrawerFilter(img: 'assets/iconImage/holi.png', name: 'Holi'),
  DrawerFilter(img: 'assets/iconImage/flute.png', name: 'Janmashtmi'),
  DrawerFilter(img: 'assets/iconImage/chrishmas.png', name: 'Marry Chrishmas'),
  DrawerFilter(img: 'assets/iconImage/new_year.png', name: 'New Year'),
  DrawerFilter(img: 'assets/iconImage/ganesha.png', name: 'Ganesh Chaturthi'),
  DrawerFilter(img: 'assets/iconImage/ind.png', name: 'Independence Day'),
];


List<SelectFrameField> selectFrameField = <SelectFrameField>[
  SelectFrameField(
      img: "assets/images/navratri.jpg", name: 'Navratri'),
  SelectFrameField(
      img: "assets/images/diwali.jpg", name: 'Diwali'),
  SelectFrameField(img: "assets/images/rakhi.jpg", name: 'Rakhi'),
  SelectFrameField(
      img: "assets/images/mkr.jpg", name: 'Makar Sankranti'),
  SelectFrameField(img: "assets/images/holi.jpg", name: 'Holi'),
  SelectFrameField(
      img: "assets/images/janmashtami.png", name: 'Janmashtmi'),
  SelectFrameField(
      img: "assets/images/chrismas.jpg", name: 'Marry Chrishmas'),
  SelectFrameField(
      img: "assets/images/year.jpeg", name: 'New Year'),
  SelectFrameField(
      img: "assets/images/ganesh.jpeg", name: 'Ganesh Chaturthi'),
  SelectFrameField(
      img: "assets/images/ind.jpg", name: 'Independence Day'),
];

List<FilterImg> filterImg = <FilterImg>[
  FilterImg(
    img: const Icon(Icons.image, color: Colors.white),
    name: 'Gallery',
  ),
  FilterImg(
    img: const Icon(Icons.filter_frames, color: Colors.white),
    name: 'Frames',
  ),
  FilterImg(
    img: const Icon(Icons.color_lens, color: Colors.white),
    name: 'Filters',
  ),
  FilterImg(
    img: const Icon(Icons.brightness_4, color: Colors.white),
    name: 'Bright',
  ),
  FilterImg(
    img: const Icon(Icons.opacity, color: Colors.white),
    name: 'Opacity',
  ),
  FilterImg(
    img: const Icon(Icons.satellite, color: Colors.white),
    name: 'Sat',
  ),
  FilterImg(
    img: const Icon(Icons.exposure, color: Colors.white),
    name: 'Expose',
  ),
  FilterImg(
    img: const Icon(Icons.text_fields_outlined, color: Colors.white),
    name: 'Text',
  ),
  FilterImg(
    img: const Icon(Icons.sticky_note_2_rounded, color: Colors.white),
    name: 'Sticker',
  ),
];
