import 'package:festival_frame/models/frame_model.dart';
import 'package:flutter/material.dart';


List frameImage = [
    "assets/images/navratri.png",
    "assets/images/diwali.jpg",
    "assets/images/rakhi.jpg",
    "assets/images/mkr.jpg",
    "assets/images/holi.png",
    "assets/images/janmashtmi.jpg",
    "assets/images/chrismas.jpg",
    "assets/images/ganesh.jpg",
    "assets/images/ind.jpg",
    // "assets/images/ram.jpg",
  ];
 
 List<FrameData> fImage = <FrameData>[
    FrameData(
      img: '',
      name: 'Navratri',
      list: [
      "assets/images/n11.png",
      // "assets/images/n12.png",
      // "assets/images/n13.png",
      "assets/images/n14.png",
      // "assets/images/n15.png",
      "assets/images/n16.png",
      // "assets/images/n17.png",
      "assets/images/n18.png",
      "assets/images/n21.png",
      "assets/images/n19.png",
      "assets/images/n20.png",
      "assets/images/n22.png",
      "assets/images/n23.png",
      "assets/images/n24.png",
      "assets/images/n25.png",
      "assets/images/n26.png",
      "assets/images/n27.png",
      "assets/images/n28.png",
      "assets/images/n29.png",
      "assets/images/n30.png",
      "assets/images/n31.png",
      "assets/images/n32.png",
      "assets/images/n33.png",
      "assets/images/n34.png",
      "assets/images/n35.png",
      // "assets/images/n1.png",
      // "assets/images/n2.png",
      // "assets/images/n3.png",
      // "assets/images/n4.png",
      // "assets/images/n5.png",
      // "assets/images/n6.png",
      // "assets/images/n7.png",
      // "assets/images/n8.png",
      // "assets/images/n9.png",
      "assets/images/n10.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Diwali',
      list: [
      // "assets/images/d1.png",
      "assets/images/d2.png",
      "assets/images/d3.png",
      // "assets/images/d4.png",
      // "assets/images/d5.png",
      "assets/images/d6.png",
      "assets/images/d7.png",
      "assets/images/d8.png",
      "assets/images/d9.png",
      "assets/images/d10.png",
      "assets/images/d11.png",
      "assets/images/d13.png",
      "assets/images/d14.png",
      "assets/images/d15.png",
      "assets/images/d16.png",
      "assets/images/d17.png",
      "assets/images/d18.png",
      "assets/images/d19.png",
      "assets/images/d20.png",
      "assets/images/d21.png",
      "assets/images/d22.png",
      "assets/images/d23.png",
      "assets/images/d24.png",
      "assets/images/d25.png",
      "assets/images/d26.png",
      "assets/images/d27.png",
      "assets/images/d28.png",
      "assets/images/d29.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Rakhi',
      list: [
      "assets/images/r1.png",
      // "assets/images/r2.png",
      // "assets/images/r3.png",
      // "assets/images/r4.png",
      "assets/images/r5.png",
      "assets/images/r6.png",
      // "assets/images/r7.png",
      "assets/images/r8.png",
      // "assets/images/r9.png",
      // "assets/images/r10.png",
      "assets/images/r11.png",
      "assets/images/r12.png",
      "assets/images/r27.png",
      "assets/images/r14.png",
      "assets/images/r34.png",
      "assets/images/r35.png",
      "assets/images/r36.png",
      // "assets/images/r15.png",
      "assets/images/r16.png",
      "assets/images/r17.png",
      "assets/images/r18.png",
      "assets/images/r28.png",
      "assets/images/r20.png",
      "assets/images/r21.png",
      "assets/images/r22.png",
      "assets/images/r23.png",
      "assets/images/r24.png",
      "assets/images/r25.png",
      "assets/images/r26.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Makar Sankranti',
      list: [
      // "assets/images/m1.png",
      // "assets/images/m2.png",
      // "assets/images/m3.png",
      // "assets/images/m5.png",
      // "assets/images/m6.png",
      "assets/images/m25.png",
      "assets/images/m26.png",
      "assets/images/m27.png",
      "assets/images/m7.png",
      "assets/images/m8.png",
      "assets/images/m9.png",
      "assets/images/m10.png",
      // "assets/images/m11.png",
      "assets/images/m12.png",
      "assets/images/m13.png",
      "assets/images/m14.png",
      "assets/images/m15.png",
      "assets/images/m16.png",
      "assets/images/m17.png",
      "assets/images/m18.png",
      "assets/images/m19.png",
      "assets/images/m20.png",
      "assets/images/m21.png",
      "assets/images/m22.png",
      "assets/images/m23.png",
      "assets/images/m24.png",
      "assets/images/m28.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Holi',
      list: [
      // "assets/images/h1.png",
      // "assets/images/h2.png",
      // "assets/images/h3.png",
      "assets/images/h20.png",
      "assets/images/h4.png",
      // "assets/images/h5.png",
      // "assets/images/h6.png",
      // "assets/images/h7.png",
      // "assets/images/h30.png",
      // "assets/images/h31.png",
      "assets/images/h8.png",
      // "assets/images/h9.png",
      // "assets/images/h10.png",
      "assets/images/h26.png",
      "assets/images/h25.png",
      "assets/images/h11.png",
      "assets/images/h12.png",
      "assets/images/h21.png",
      "assets/images/h13.png",
      "assets/images/h22.png",
      "assets/images/h23.png",
      "assets/images/h24.png",
      "assets/images/h14.png",
      "assets/images/h15.png",
      "assets/images/h16.png",
      "assets/images/h29.png",
      "assets/images/h27.png",
      "assets/images/h28.png",
      "assets/images/h32.png",
      "assets/images/h33.png",
      "assets/images/h34.png",
      "assets/images/h35.png",
      "assets/images/h18.png",
      "assets/images/h19.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Janmashtmi',
      list: [
      // "assets/images/j1.png",
      // "assets/images/j2.png",
      "assets/images/j3.png",
      // "assets/images/j4.png",
      "assets/images/j5.png",
      // "assets/images/j6.png",
      "assets/images/j7.png",
      "assets/images/j8.png",
      // "assets/images/j9.png",
      "assets/images/j10.png",
      "assets/images/j11.png",
      // "assets/images/j12.png",
      "assets/images/j23.png",
      "assets/images/j20.png",
      "assets/images/j21.png",
      "assets/images/j22.png",
      "assets/images/j19.png",
      "assets/images/j15.png",
      "assets/images/j16.png",
      "assets/images/j17.png",
      "assets/images/j24.png",
      "assets/images/j25.png",
      "assets/images/j26.png",
      "assets/images/j27.png",
      "assets/images/j28.png",
      "assets/images/j29.png",
      "assets/images/j30.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'marry Chrishmas',
      list: [
      // "assets/images/c1.png",
      // "assets/images/c2.png",
      // "assets/images/c3.png",
      // "assets/images/c4.png",
      // "assets/images/c5.png",
      "assets/images/c6.png",
      // "assets/images/c7.png",
      "assets/images/c8.png",
      "assets/images/c9.png",
      // "assets/images/c10.png",
      "assets/images/c11.png",
      "assets/images/c12.png",
      // "assets/images/c13.png",
      // "assets/images/c14.png",
      // "assets/images/c15.png",
      "assets/images/c16.png",
      "assets/images/c17.png",
      "assets/images/c20.png",
      "assets/images/c21.png",
      "assets/images/c22.png",
      "assets/images/c23.png",
      "assets/images/c24.png",
      "assets/images/c25.png",
      "assets/images/c26.png",
      "assets/images/c27.png",
      "assets/images/c28.png",
      "assets/images/c29.png",
      "assets/images/c30.png",
      "assets/images/c31.png",
      "assets/images/c32.png",
      "assets/images/c33.png",
      "assets/images/c34.png",
      "assets/images/c35.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Ganesh Chaturthi',
      list: [
      "assets/images/g1.png",
      // "assets/images/g4.png",
      "assets/images/g3.png",
      "assets/images/g11.png",
      "assets/images/g5.png",
      "assets/images/g6.png",
      "assets/images/g12.png",
      "assets/images/g13.png",
      "assets/images/g14.png",
      "assets/images/g8.png",
      "assets/images/g9.png",
      "assets/images/g17.png",
      "assets/images/g15.png",
      "assets/images/g16.png",
      "assets/images/g18.png",
      "assets/images/g19.png",
      "assets/images/g20.png",
      "assets/images/g21.png",
      "assets/images/g22.png",
      "assets/images/g23.png",
      "assets/images/g24.png",
      "assets/images/g25.png",
      "assets/images/g26.png",
      "assets/images/g27.png",
      "assets/images/g28.png",
      "assets/images/g29.png",
      "assets/images/g30.png",
      "assets/images/g31.png",
    ],
    ),
    FrameData(
      img: '',
      name: 'Independence Day',
      list: [
      "assets/images/i1.png",
      // "assets/images/i2.png",
      "assets/images/i3.png",
      // "assets/images/i4.png",
      "assets/images/i5.png",
      "assets/images/i14.png",
      "assets/images/i6.png",
      // "assets/images/i7.png",
      "assets/images/i8.png",
      // "assets/images/i9.png",
      "assets/images/i10.png",
      "assets/images/i16.png",
      "assets/images/i15.png",
      "assets/images/i12.png",
      "assets/images/i22.png",
      "assets/images/i17.png",
      "assets/images/i18.png",
      "assets/images/i19.png",
      "assets/images/i20.png",
      "assets/images/i21.png",
      "assets/images/i23.png",
      "assets/images/i25.png",
      "assets/images/i26.png",
      "assets/images/i27.png",
      "assets/images/i28.png",
      "assets/images/i29.png",
      "assets/images/i30.png",
      "assets/images/i31.png",
      "assets/images/i32.png",
      "assets/images/i33.png",
      "assets/images/i34.png",
      "assets/images/i35.png",
      "assets/images/i36.png",
      "assets/images/i37.png",
    ],
    ),
    // FrameData(
    //   img: '',
    //   name: 'Ram Navami',
    //   list: [
    //   "assets/images/ram1.png",
    //   "assets/images/ram2.png",
    //   "assets/images/ram3.png",
    // ],
    // ),
  ];

  List<String> festivleName = [
    "Navratri",
    "Diwali",
    "Rakhi",
    "Makar Sankranti",
    "Holi",
    "Janmashtmi",
    "marry Chrishmas",
    "Ganesh Chaturthi",
    "Independence Day",
    // "Ram Navami",
  ];

  List icons = [
    "assets/iconImage/dandiya.png",
    "assets/iconImage/diya.png",
    "assets/iconImage/rakhi.png",
    "assets/iconImage/kite.png",
    "assets/iconImage/holi.png",
    "assets/iconImage/flute.png",
    "assets/iconImage/chrishmas.png",
    "assets/iconImage/ganesha.png",
    "assets/iconImage/ind.png",
    // "assets/iconImage/ram.png",
  ];

  List imageColors = const [
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    Color.fromARGB(255, 208, 197, 206),
    // Color.fromARGB(255, 208, 197, 206),
  ];
  
